name = "KaguyaSPViewer"
uuid = "a704fdaf-d37c-4bff-b48d-548225e3cb47"
authors = ["Z.M. Vig <zvig@umd.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"

[compat]
julia = "1"
GLMakie = "0.9.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
