name = "KaguyaSPViewer"
uuid = "a704fdaf-d37c-4bff-b48d-548225e3cb47"
authors = ["Z.M. Vig <zvig@umd.edu> and contributors"]
version = "1.0.0-DEV"

[deps]
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
LazySets = "b4f0291d-fe17-52bc-9479-3d1a343d9043"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Interpolations = "0.15.1"
LazySets = "2.11.4"
GLMakie = "0.9.8"
Statistics = "1.9.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
